profile=high-quality
vo=gpu-next

scale=ewa_lanczossharp
cscale=ewa_lanczossharp
dscale=mitchell

scale-antiring=0.7
cscale-antiring=0.7
dscale-antiring=0.7

deband=yes
deband-iterations=2
deband-threshold=35
deband-range=16
deband-grain=5

video-sync=display-resample
interpolation=yes
tscale=oversample
