# GENERAL
general {
  hide_cursor = true
  immediate_render = true
}

animations {
  animation = fadeIn, 0, 0, linear
}

# BACKGROUND
background {
  monitor =
  path = $HOME/.config/hypr/wallpaper.jpg
  blur_passes = 2
  color = rgb(1e1e2e)
}


# Date
label {
    monitor =
    text = cmd[update:18000000] echo "<b> "$(date +'%A, %-d %B')" </b>"
    color = rgb(cdd6f4)
    font_size = 16
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, -150
    halign = center
    valign = center
}

# Hour-Time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H")"
#    text = cmd[update:1000] echo "$(date +"%I")" #AM/PM
	#color = rgba(255, 185, 0, .8)
    color = rgb(cdd6f4)
    font_size = 200
    font_family = JetBrainsMono Nerd Font ExtraBold 
    position = 0, -60
    halign = center
    valign = top
}

# Minute-Time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%M")"
    #color = rgba(15, 10, 222, .8)
    color = rgb(bac2de)
    font_size = 200
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, -350
    halign = center
    valign = top
}

# Seconds-Time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%S")"
#    text = cmd[update:1000] echo "$(date +"%S %p")" #AM/PM
    color = rgb(b4befe)
    font_size = 35
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, -350
    halign = center
    valign = top
}

# Battery
label {
    monitor =
    text = cmd[update:100000] echo "$(($(cat /sys/class/power_supply/BAT1/capacity) > 100 ? 100 : $(cat /sys/class/power_supply/BAT1/capacity)))%"
    color = rgb(b4befe)
    font_size = 15
    font_family = Product Sans Medium
    position = -15, -10
    halign = right
    valign = top
}


# USER
label {
    monitor =
    text =   $USER
    color = rgb(cdd6f4)
    font_size = 24
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 150
    halign = center
    valign = bottom
}

# INPUT FIELD
input-field {
  monitor =
  size = 300, 60
  outline_thickness = 2
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = rgb(b4befe)
  inner_color = rgb(1e1e2e)
  font_color = rgb(cdd6f4)
  fade_on_empty = true
  placeholder_text = 
  hide_input = false
  check_color = rgb(a6e3a1)
  fail_color = rgb(eba0ac)
  capslock_color = rgb(f9e2af)
  position = 0, 50
  halign = center
  valign = bottom
}
