general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
    after_sleep_cmd = sleep 2 && gsettings set org.gnome.desktop.interface cursor-size 21
}

listener {
    # timeout = 300                                 # 5min
    on-timeout = loginctl lock-session            # lock screen when timeout has passed
}

listener {
    # timeout = 1800                                # 30min
    on-timeout = systemctl suspend                # suspend pc
}
