general {
    lock_cmd = hyprctl dispatch global quickshell:triggerSessionLock
    before_sleep_cmd = hyprctl dispatch global quickshell:triggerSessionLock
    after_sleep_cmd = hyprctl dispatch dpms on && sleep 2 && gsettings set org.gnome.desktop.interface cursor-size 21
}

# listener {
#     # timeout = 300                                 # 5min
#     on-timeout = loginctl lock-session
# }
# 
# listener {
#     # timeout = 1800                                # 30min
#     on-timeout = systemctl suspend
# }
